# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

# system "vagrant plugin update"
# required_plugins = %w(vagrant-digitalocean)
# required_plugins.each do |plugin|
#   system "NOKOGIRI_USE_SYSTEM_LIBRARIES=1 vagrant plugin install #{plugin}" unless Vagrant.has_plugin? plugin
# end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.define "puppet-server" do |server|
    server.vm.hostname = "puppet-server"
    server.vm.network "private_network", ip: "33.33.44.11"
    server.vm.provider "virtualbox" do |provider|
      provider.name = "puppet-server"
      provider.customize ["modifyvm", :id, "--memory", "1024"]
    end

  end

  config.vm.define "puppet-agent" do |agent|
    $script = <<SCRIPT
wget https://apt.puppetlabs.com/puppetlabs-release-pc1-trusty.deb
sudo dpkg -i puppetlabs-release-pc1-trusty.deb 
sudo apt-get -i update
sudo apt-get -y autoremove
sudo apt-get install -y puppet-agent
SCRIPT

    agent.vm.hostname = "puppet-agent"
    agent.vm.network "private_network", ip: "33.33.44.22"
    agent.vm.provider "virtualbox" do |provider|
      provider.name = "puppet-agent"
      provider.customize ["modifyvm", :id, "--memory", "1024"]
    end
    config.vm.provision "shell", inline: $script

  end

end
