---
  - name: Update apt cache if needed
    apt: update_cache=yes cache_valid_time=3600

  - name: Upgrade OS
    apt: upgrade=dist force=yes

  - name: Upgrade OS
    apt: upgrade=full force=yes

  - name: Check if packages need to be autoremoved
    command: apt-get --dry-run autoremove
    register: check_autoremove
    changed_when: False

  - name: Autoremove unused packages
    command: apt-get -y autoremove
    when: "'packages will be REMOVED' in check_autoremove.stdout"

  - name: Install needed packages
    apt: pkg={{item}} state=installed
    with_items:
      - cron
      - logrotate
      - curl
      - git
      - update-motd
      - tmux
      - ufw
      - fail2ban
      - logwatch
      - update-manager-core

  - name: Removed unwanted services
    apt: name={{item}} state=absent
    with_items:
      - postfix

  - name: Disable periodic OS update checks
    lineinfile: dest=/etc/apt/apt.conf.d/10periodic regexp="^APT::Periodic::Update-Package-Lists \"1\"" line="APT::Periodic::Update-Package-Lists \"0\";" state=present

  - name: Create the deploy user
    user: name={{user}} comment="deploy user" generate_ssh_key=yes ssh_key_bits=2048 state=present password={{password}} shell=/bin/bash

  - name: Copy ssh keys to the user's .ssh directory
    copy: src=ita.pub dest=/home/{{user}}/.ssh/authorized_keys mode=0700 owner={{user}} group={{user}}

  - name: Set {{user}} as sudoer
    lineinfile: dest=/etc/sudoers line="{{user}} ALL=(ALL) NOPASSWD:ALL"

  - name: remove ubuntu's user
    user: name=ubuntu state=absent remove=yes

  - name: Set vi preferences
    copy: src=vimrc dest=/home/{{user}}/.vimrc owner={{user}}

  - name: FW Allow everything
    ufw: state=enabled policy=allow

  - name: Disallow password authentication
    lineinfile: dest=/etc/ssh/sshd_config
                regexp="^PasswordAuthentication"
                line="PasswordAuthentication no"
                state=present
    notify: Restart ssh

  - name: Disallow root SSH access
    lineinfile: dest=/etc/ssh/sshd_config
                regexp="^PermitRootLogin"
                line="PermitRootLogin no"
                state=present
    notify: Restart ssh

  - name: Mail logwatch reports
    lineinfile: dest=/etc/cron.daily/00logwatch
                regexp="^/usr/sbin/logwatch"
                line="/usr/sbin/logwatch --output mail --mailto ihassin@mac.com --detail high"
                state=present
